// FriendsPage.js
import React from 'react';

function FriendsPage() {
  return (
    <div className="middle-content">
      <h1>Friends Page</h1>
      <p>Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page Friends Page 
      </p>
    </div>
  );
}

export default FriendsPage;
